FROM node:slim

# Set the work directory to app folder. 
# We will be copying our code here
WORKDIR /app/client

#Copy package.json file in the app/client folder inside container
COPY package.json .

# Install the dependencies in the container
RUN yarn install

# Copy the rest of the code in the container
COPY . .

CMD ["yarn", "app.tsx"]

EXPOSE 3000