FROM python:slim

WORKDIR /app/server

# Install python3 and venv
# RUN apt-get update \
    # && sudo apt install python3.11-venv \
    # && sudo apt-get install -y python3-pip \
    # && sudo apt-get install -y python3-venv \
    # && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy everything else
COPY . .

CMD ["python", "app.py"]
